/**
 * @desc elements
 * @author MiyueFE <https://github.com/miyuesc>
 * @since 2024/9/5 09:05
 */

export default {
  "Transaction": "事务",
  "Business rule task": "规则任务",
  "Call activity": "引用流程",
  "Data object reference": "数据对象引用",
  "Data store reference": "数据存储引用",
  "Empty pool/participant": "空泳道",
  "Empty pool/participant (removes content)": "清空泳道（删除内容）",

  "Gateway": "网关",
  "Complex gateway": "复杂网关",
  "Parallel gateway": "并行网关",
  "Event-based gateway": "事件网关",
  "Exclusive gateway": "独占网关",
  "Inclusive gateway": "包容网关",

  "Task": "任务",
  "User task": "用户任务",
  "Receive task": "接收任务",
  "Script task": "脚本任务",
  "Send task": "发送任务",
  "Service task": "服务任务",
  "Manual task": "手动任务",

  "Sequence flow": "顺序流",
  "Default flow": "默认流",
  "Conditional flow": "条件流",

  "Intermediate throw event": "中间抛出事件",
  "Link intermediate catch event": "中间链接捕获事件",
  "Link intermediate throw event": "中间链接抛出事件",
  "Message boundary event": "消息边界事件",
  "Message boundary event (non-interrupting)": "消息边界事件 (非中断)",
  "Message intermediate catch event": "中间消息捕获事件",
  "Message intermediate throw event": "中间消息抛出事件",
  "Signal boundary event": "信号边界事件",
  "Signal boundary event (non-interrupting)": "信号边界事件 (非中断)",
  "Signal intermediate catch event": "中间信号捕获事件",
  "Signal intermediate throw event": "中间信号抛出事件",
  "Timer boundary event": "定时边界事件",
  "Timer boundary event (non-interrupting)": "定时边界事件 (非中断)",
  "Timer intermediate catch event": "中间定时捕获事件",
  "Cancel boundary event": "取消边界事件",
  "Compensation boundary event": "补偿边界事件",
  "Compensation intermediate throw event": "中间补偿抛出事件",
  "Conditional boundary event": "条件边界事件",
  "Conditional boundary event (non-interrupting)": "条件边界事件 (非中断)",
  "Conditional intermediate catch event": "中间条件捕获事件",
  "Error boundary event": "错误边界事件",
  "Escalation boundary event": "升级边界事件",
  "Escalation boundary event (non-interrupting)": "升级边界事件 (非中断)",
  "Escalation intermediate throw event": "中间升级抛出事件",

  "End event": "结束事件",
  "Signal end event": "信号结束事件",
  "Message end event": "消息结束事件",
  "Terminate end event": "终止结束事件",
  "Error end event": "错误结束事件",
  "Escalation end event": "升级结束事件",
  "Compensation end event": "补偿结束事件",
  "Cancel end event": "取消结束事件",

  "Start event": "开始事件",
  "Signal start event": "信号开始事件",
  "Signal start event (non-interrupting)": "信号开始事件 (非中断)",
  "Message start event": "消息开始事件",
  "Message start event (non-interrupting)": "消息开始事件 (非中断)",
  "Timer start event": "定时开始事件",
  "Timer start event (non-interrupting)": "定时开始事件 (非中断)",
  "Escalation start event": "升级开始事件",
  "Escalation start event (non-interrupting)": "升级开始事件 (非中断)",
  "Error start event": "错误开始事件",
  "Compensation start event": "补偿开始事件",
  "Conditional start event": "条件开始事件",
  "Conditional start event (non-interrupting)": "条件开始事件 (非中断)",

  "Sub-process": "子流程",
  "Event sub-process": "事件子流程",
  "Sub-process (collapsed)": "折叠的子流程",
  "Sub-process (expanded)": "展开的子流程",
}
