export default {
  // zeebe tooltips
  "Define who the task is assigned to. One or all of the following attributes can be specified simultaneously. ": "定义任务分配人。可以同时指定一个或多个属性。",
  "User task documentation": "用户任务文档",
  "Conditions documentation": "条件文档",
  "Business rule task documentation": "业务规则任务文档",
  "Script task documentation": "脚本任务文档",
  "User task form documentation": "用户任务表单文档",
  "Send task documentation": "发送任务文档",
  "Receive task documentation": "接收任务文档",
  "Message event documentation": "消息事件文档",
  "Call activity documentation": "调用活动文档",
  "Service task documentation": "服务任务文档",
  "Message throw event documentation": "抛出消息事件文档",
  "Multi instance documentation": "多重实例文档",
  "Error event documentation": "错误事件文档",
  "Input mappings documentation": "输入映射文档",
  "Output mappings documentation": "输出映射文档",
  ") and the ": "和 ",
  " expression (e.g. ": "表达式（例如：",
  ")": "）",
  ").": "）。",
  " to subscribe to. ": "来订阅。",
  " or ": "或 ",
  " ).": "）。",
  "send": "发送",
  "and": "和",

  "Learn more.": "了解更多。",
  "Learn more how to ": "了解更多如何 ",
  "Learn how to define conditions.": "了解如何定义条件。",
  "receive messages. ": "接收消息。",
  "Define a boolean condition expression that defines when this flow is taken. ": "定义一个布尔条件表达式，用于定义何时启动此流程。",
  "Evaluate a business rule, for example a DMN. To add a custom implementation, use a job worker. ": "执行业务规则，例如 DMN。要添加自定义实现，请使用 job worker。",
  "Implement a script task using an inline FEEL expression. To add a custom implementation, use a job worker. ": "使用内联 FEEL 表达式实现脚本任务。要添加自定义实现，请使用 job worker。",
  "Link or embed a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify a form key. ": "链接或嵌入 Camunda Forms 编辑器创建的表单。要将自定义表单、应用程序或 URL 关联到用户任务，请指定表单 key。",
  "Define the name of the message (e.g. ": "定义消息名称（例如：",
  "Define the ID of the process to call (e.g. ": "定义要调用的流程 ID（例如：",
  "Specify which job workers handle the task work to execute a service (e.g. ": "指定要执行的服务（例如：",
  "Specify which job workers handle the task work to evaluate business rules. ": "指定要执行的业务规则。",
  "Specify which job workers handle the task work to execute a script. ": "指定要执行的脚本。",
  "Specify which job workers handle the task work to send a message (e.g. ": "指定要发送的消息（例如：",
  "Specify which job workers handle the event work. ": "指定要处理的事件。",
  "Execute this task for each element of a given collection. ": "对给定集合的每个元素执行此任务。",
  "Define an input collection expression that defines the collection to iterate over (e.g. ": "定义迭代集合表达式（例如：",
  "To collect the output define the output collection and the output element expressions. ": "为收集输出定义输出集合和输出元素表达式。",
  "Define an error code (e.g. ": "定义错误代码（例如：",
  "Create a new local variable in the scope of this task. ": "在此任务的作用域内创建一个新的本地变量。",
  "Customize how result variables are merged into the global scope of the process instance. ": "自定义如何将结果变量合并到流程实例的全局作用域。",


}
