export default {
  "ID": "ID",
  "Key": "key",
  "Implementation": "实现方式",
  "Errors": "错误",
  "User assignment": "用户分配",
  "Script": "脚本",
  "Called element": "调用元素",
  "Condition": "条件",
  "Start initiator": "启动器",
  "External task": "外部任务",
  "Asynchronous continuations": "异步延续",
  "Job execution": "执行作业",
  "Candidate starter": "候选启动器",
  "Field injections": "字段注入",
  "History cleanup": "历史清除",
  "Tasklist": "任务列表",
  "In mappings": "输入映射",
  "Out mappings": "输出映射",
  "In mapping propagation": "输入映射传播",
  "Out mapping propagation": "输出映射传播",
  "Process variables": "流程变量",
  "Form fields": "表单字段",
  "Business key": "业务 key",
  "Forms": "表单",
  "Execution listeners": "执行监听器",
  "Task listeners": "任务监听器",
  "Inputs": "输入",
  "Outputs": "输出",
  "Connector inputs": "连接器输入",
  "Connector outputs": "连接器输出",
  "Extension properties": "扩展属性",
  "Decision reference": "决策引用",
  "Binding": "绑定",
  "Version": "版本号",
  "Version tag": "版本标签",
  "Tenant ID": "团队 ID",
  "Result variable": "结果变量",
  "collectEntries (List<Object>)": "入口集合（List<Object>）",
  "resultList (List<Map<String, Object>>)": "结果列表（List<Map<String, Object>>）",
  "singleEntry (TypedValue)": "信号入口（TypedValue）",
  "singleResult (Map<String, Object>)": "信号结果（Map<String, Object>）",
  "Map decision result": "映射决策结果",
  "Message": "消息",
  "Code variable": "编码变量",
  "Message variable": "消息变量",
  "Priority": "权重",
  "String": "字符串",
  "Expression": "表达式",
  "Delegate expression": "代理表达式",
  "Config": "配置",
  "Form key": "表单 key",
  "Form reference": "表单引用",
  "Time to live": "存活时间",
  "Java class": "Java 类",
  "List values": "枚举列表",
  "Map": "映射",
  "List": "列表",
  "create": "创建",
  "assignment": "指派",
  "complete": "完成",
  "delete": "删除",
  "update": "更新",
  "timeout": "超时",
  "take": "采用",
  "start": "开始",
  "end": "结束",
  "Event type": "事件类型",
  "Listener ID": "监听器 ID",
  "Listener type": "监听器类型",
  "Field injection": "字段注入",
  "<empty>": "空",
  "Map entries": "映射入口",
  "Value": "值",
  "Startable": "可启动",

  "deployment": "开发版",
  "latest": "最新正式版",
  "version": "版本号",
  "versionTag": "版本标签",

  "Define the name of the variable that will contain the error code.": "定义将包含错误代码的变量的名称。"
}
