export default {
  "ID": "ID",
  "Key": "key",
  "Implementation": "实现方式",
  "Errors": "错误",
  "User assignment": "用户分配",
  "Script": "脚本",
  "Called element": "调用元素",
  "Condition": "条件",
  "Start initiator": "启动器",
  "External task": "外部任务",
  "Asynchronous continuations": "异步延续",
  "Before": "异步前",
  "After": "异步后",
  "Exclusive": "独占",
  "Job execution": "执行作业",
  "Candidate starter": "候选启动器",
  "Field injections": "字段注入",
  "History cleanup": "历史清除",
  "Tasklist": "任务列表",
  "In mappings": "输入映射",
  "Out mappings": "输出映射",
  "In mapping propagation": "输入映射传播",
  "Out mapping propagation": "输出映射传播",
  "Process variables": "流程变量",
  "Form fields": "表单字段",
  "Business key": "业务关键字",
  "Forms": "表单",
  "Execution listeners": "执行监听器",
  "Task listeners": "任务监听器",
  "Inputs": "输入",
  "Outputs": "输出",
  "Connector inputs": "连接器输入",
  "Connector outputs": "连接器输出",
  "Extension properties": "扩展属性",
  "Decision reference": "决策引用",
  "Binding": "绑定",
  "Version": "版本号",
  "Version tag": "版本标签",
  "Tenant ID": "团队 ID",
  "Result variable": "结果变量",
  "collectEntries (List<Object>)": "入口集合（List<Object>）",
  "resultList (List<Map<String, Object>>)": "结果列表（List<Map<String, Object>>）",
  "singleEntry (TypedValue)": "信号入口（TypedValue）",
  "singleResult (Map<String, Object>)": "信号结果（Map<String, Object>）",
  "Map decision result": "映射决策结果",
  "Message": "消息",
  "Code variable": "编码变量",
  "Message variable": "消息变量",
  "Priority": "权重",
  "String": "字符串",
  "Expression": "表达式",
  "Delegate expression": "代理表达式",
  "Config": "配置",
  "Form key": "表单 key",
  "Form reference": "表单引用",
  "Time to live": "存活时间",
  "Java class": "Java 类",
  "List values": "枚举列表",
  "Map": "映射",
  "List": "列表",
  "create": "创建",
  "assignment": "指派",
  "complete": "完成",
  "delete": "删除",
  "update": "更新",
  "timeout": "超时",
  "take": "采用",
  "start": "开始",
  "end": "结束",
  "Event type": "事件类型",
  "Listener ID": "监听器 ID",
  "Listener type": "监听器类型",
  "Field injection": "字段注入",
  "<empty>": "空",
  "Map entries": "映射入口",
  "Value": "值",
  "Startable": "可启动",
  "Constraints": "约束条件",
  "Properties": "属性列表",
  "Initiator": "启动器",
  "Retry time cycle": "重试时间周期",
  "Candidate starter groups": "候选启动组",
  "Candidate starter users": "候选启动用户",

  "Camunda Forms": "Camunda 表单",
  "Embedded or External Task Forms": "嵌入或者外部任务表单",
  "Generated Task Forms": "生成任务表单",
  "Label": "标签名",
  "Default value": "默认值",
  "Script type": "脚本类型",

  "deployment": "开发版",
  "latest": "最新正式版",
  "version": "版本号",
  "versionTag": "版本标签",
  "External": "外部",
  "Topic": "外部",
  "Connector": "连接器",
  "Connector ID": "连接器 ID",

  "External resource": "外部资源",
  "Inline script": "内联脚本",
  "Resource": "资源地址",
  "Format": "格式",
  "Local": "本地",
  "Source": "源",
  "Target": "目标",
  "Case ref": "参考案例",

  "Variable name": "变量名称",
  "Local variable name": "本地变量名称",
  "Process variable name": "流程变量名称",
  "Assignment type": "分配类型",
  "String or expression": "字符串或表达式",
  "Condition expression": "条件表达式",
  "Condition Expression": "条件表达式",
  "Throw expression": "异常抛出表达式",
  "Source expression": "源表达式",

  "Created in": "创建自",
  "Refers to the process variable name": "引用流程变量名称",
  "Specify more than one group as a comma separated list.": "以逗号分隔列表的形式指定多个组。",
  "Specify more than one user as a comma separated list.": "以逗号分隔列表的形式指定多个用户。",
  "Start typing \"${}\" to create an expression.": "开始键入 \"${}\" 以创建表达式。",
  "The due date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).": "截止日期为 EL 表达式 (例如 ${someDate}) 或 ISO 格式日期 (例如 2015-06-26T09:54:00)。",
  "The follow up date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).": "跟进日期为 EL 表达式 (例如 ${someDate}) 或 ISO 格式日期 (例如 2015-06-26T09:54:00)。",
  "Define the name of the variable that will contain the error code.": "定义将包含错误代码的变量的名称。"
}
